const theme = {
  maxWidth: "1440px",
  colors: {
    dark: "#f4effc",
    black: "#FFFFFF",
    white: "#1f1235", 
    darkenedWhite: "#fbdd74",
    red: "#ff6e6c", 
    brightRed: "red",
    hoveredRed: "#fbdd74",
    darkBlue: "#fbdd74",
    hoveredBlue: "orange",
    lightGrey: "#1b1425",
    mediumGrey: "#1f1235",
    darkGrey: "#1b1425",
    thinGrey: "#ff6e6c",
    footer: "#e2daeb",
    loadingBack: "#e2daeb",
  },
  fontSizes: {
    xs: "16px",
    sm: "19px",
    xl: "67px",
  },
  easing: "cubic-bezier(0.645, 0.045, 0.355, 1)",
  srConfig: (delay = 200) => ({
    origin: "bottom",
    distance: "20px",
    duration: 500,
    delay,
    rotate: { x: 0, y: 0, z: 0 },
    opacity: 0,
    scale: 1,
    easing: "cubic-bezier(0.645, 0.045, 0.355, 1)",
    mobile: true,
    reset: false,
    useDelay: "always",
    viewFactor: 0.25,
    viewOffset: { top: 0, right: 0, bottom: 0, left: 0 },
  }),
};

export default theme;
